name: pokedex
description: Pokédex app usando arquitetura profissional Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Requisições HTTP
  dio: ^5.9.0

  # Manipulação de Dados
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Utilitários
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting e análise de código
  flutter_lints: ^3.0.0

  # Code generation
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true

  # Fontes (Poppins - você pode baixar do Google Fonts)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
